### ISSUE TITLE
Windows binary ?

### ISSUE THREAD

**Issue by fulljackz** [federicoiosue/omni-notes-desktop#12]
Hi,
I do not know if this is the right place to post this kind of issue.

Is it possible to have a windows binary directly on the github repo. I do not have any time to install devel environment and more, I can't do it on my pro laptop.

Hope you'll accept. 

Cheers.

**Comment by federicoiosue** [comment]
You can find the latest **preview release** into [releases](https://github.com/federicoiosue/omni-notes-desktop/releases) page but that one is pretty much outdated and have some issues that I fixed in the meantime.

You could give a look at that while the next one will be ready (not so fast due to the fact that I'm quite concentrated on the Android app these days).

**Comment by fulljackz** [comment]
Oh ok, thank for your answer, I did not find this release (or did not search enough).
